#!/bin/env echo "Warning: this file should be sourced"
cd $DIR
. PUB.sh
. install_env.sh
cd $DIR
##### Public #####

HADOOP_PORT_PREFIX=38

##### tar package
# $0 prefix
find_version()
{
  echo `ls -l tar/${1}* | sed "s:^.*tar/::;s:-[^-]*$::;q"`
}
find_tar()
{
  echo `ls tar/${1}*.tar.gz | sed "s:^.*tar/::;q"`
}
find_it()
{
  echo `ls tar/${1} | sed "s:^.*tar/::;q"`
}
JAVA_VERSION=`find_version jdk`
IS_32 && JAVA_TAR=${JAVA_VERSION}-32.tar.gz || JAVA_TAR=${JAVA_VERSION}-64.tar.gz

ANT_VERSION=`find_version apache-ant`
ANT_TAR=${ANT_VERSION}-bin.tar.gz

MAVEN_VERSION=`find_version apache-maven`
MAVEN_TAR=${MAVEN_VERSION}-bin.tar.gz

IS_32 && LZO_TAR=lzo-32.tar.gz || LZO_TAR=lzo-64.tar.gz

HADOOP_LZO_TAR=hadoop-lzo.tar.gz

IS_32 && FUSE_DFS_TAR=fuse-dfs-32.tar.gz || FUSE_DFS_TAR=fuse-dfs-64.tar.gz

HADOOP_TAR=`find_tar hadoop*cdh`
HADOOP_VERSION=${HADOOP_TAR%.tar.gz}

HIVE_TAR=`find_tar hive*cdh`
HIVE_VERSION=${HIVE_TAR%.tar.gz}

#HIVE_MYSQL=mysql-connector-java-5.1.16-bin.jar
MYSQL_JAR=`find_it "mysql-*.jar"`

HUE_TAR=`find_tar hue*cdh`
HUE_VERSION=${HUE_TAR%.tar.gz}

HBASE_TAR=`find_tar hbase*cdh`
#HBASE_VERSION=hbase-0.90.3-cdh3u1
HBASE_VERSION=${HBASE_TAR%.tar.gz}

# core-site
HADOOP_TMP_DIR="$HOME/hadoop_data"
FS_DEFAULT_NAME="hdfs://$NN:${HADOOP_PORT_PREFIX}900"

# hdfs-site
DFS_SECONDARY_HTTP_ADDRESS="0.0.0.0:${HADOOP_PORT_PREFIX}090"
DFS_DATANODE_HANDLER_COUNT="3"
DFS_HTTP_ADDRESS="$NN:${HADOOP_PORT_PREFIX}070"
DFS_REPLICATION="2"
DFS_NAMENODE_HANDLER_COUNT="5"
DFS_DATANODE_ADDRESS="0.0.0.0:${HADOOP_PORT_PREFIX}010"
DFS_DATANODE_IPC_ADDRESS="0.0.0.0:${HADOOP_PORT_PREFIX}020"
DFS_DATANODE_HTTP_ADDRESS="0.0.0.0:${HADOOP_PORT_PREFIX}075"
DFS_HTTPS_ADDRESS="0.0.0.0:${HADOOP_PORT_PREFIX}470"
DFS_DATANODE_HTTPS_ADDRESS="0.0.0.0:${HADOOP_PORT_PREFIX}475"
DFS_THRIFT_PORT="${HADOOP_PORT_PREFIX}903"
DFS_THRIFT_ADDRESS="0.0.0.0:$DFS_THRIFT_PORT"
DFS_BLOCK_SIZE="134217728"
DFS_BALANCE_BANDWIDTHpERsEC="20000000"

# mapred-site
HADOOP_JOB_HISTORY_LOCATION=""
HADOOP_JOB_HISTORY_USER_LOCATION=""
MAPRED_JOB_TRACKER="$JT:${HADOOP_PORT_PREFIX}901"
MAPRED_MAP_TASKS="2"
MAPRED_REDUCE_TASKS="1"
MAPRED_TASKTRACKER_MAP_TASKS_MAXIMUM="6"
MAPRED_TASKTRACKER_REDUCE_TASKS_MAXIMUM="2"
MAPRED_JOB_TRACKER_HTTP_ADDRESS="0.0.0.0:${HADOOP_PORT_PREFIX}030"
MAPRED_TASK_TRACKER_HTTP_ADDRESS="0.0.0.0:${HADOOP_PORT_PREFIX}060"
JOBTRACKER_THRIFT_PORT="${HADOOP_PORT_PREFIX}904"
JOBTRACKER_THRIFT_ADDRESS="0.0.0.0:$JOBTRACKER_THRIFT_PORT"

# hive-site
HIVE_METASTORE_LOCAL="true"
METASTORE="hive_metastore"
JAVAX_JDO_OPTION_CONNECTIONURL="jdbc:mysql://192.168.22.30:3306/$METASTORE?createDatabaseIfNotExist=true"
HIVE_METASTORE_WAREHOUSE_DIR="/warehouse"
MYSQL_USERNAME="root"
MYSQL_PASSWORD="root"
HIVE_EXEC_COMPRESS_INTERMEDIATE="true"
MAPRED_COMPRESS_MAP_OUTPUT="true"
MAPRED_OUTPUT_COMPRESSION_TYPE="BLOCK"
HIVE_INPUT_FORMAT="org.apache.hadoop.hive.ql.io.HiveInputFormat"

# hue.ini
WEBSERVER_HTTP_HOST="0.0.0.0"
WEBSERVER_HTTP_PORT="${HADOOP_PORT_PREFIX}088"
# do not include char "#" in SECRET_KEY
SECRET_KEY="jFE93j;2[290-eiw.KEiwN2s3['d;/.q[eIW^y3e=+Iei*@Mn<qW5o"
HUE_MYSQL_HOST="192.168.22.30"
HUE_MYSQL_PORT="3306"
HUE_MYSQL_USERNAME="root"
HUE_MYSQL_PASSWORD="root"
HUE_DB_NAME="hue_db"
DFS_PORT="${HADOOP_PORT_PREFIX}900"
DFS_HTTP_PORT="${HADOOP_PORT_PREFIX}070"

# hue-beeswax.ini
BEESWAX_META_SERVER_PORT="${HADOOP_PORT_PREFIX}083"
BEESWAX_SERVER_PORT="${HADOOP_PORT_PREFIX}082"

HBASE_ROOTDIR="$FS_DEFAULT_NAME/hbase"
HBASE_TMP_DIR="$HOME/hbase_data"
HBASE_ZOOKEEPER_QUORUM="platform30,platform31,platform32,platform33,platform34"

